# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
